### ISSUE TITLE
Image is blurry/not focused at the start

### ISSUE THREAD

**Issue by ssfking** [heitorfr/ios-image-editor#22]
When first going into the image editing screen, the image appears blurry/ not focused for a couple seconds. Great library overall, but this bug will need to be fixed. Thanks!

**Comment by ssfking** [comment]
Seems like problem here I did not set previewImage to anything. If the previewImage property is set to thumbnail, it appears not as blurry; if set to the same as the source image, there is no blurriness at all (perfect). Is there any downside/bugs in setting the previewImage as the same image as the source image?

**Comment by heitorfr** [comment]
Hi. If you set the previewImage as the same as the sourceImage you may be ok, but you may experience performance issues. The problem here is that I should not draw a image bigger than 1024x1024. 
If you set previewImage to be the same as sourceImage, you probably go over this (soft) limit. Check UIImage documentation: 

"You should avoid creating UIImage objects that are greater than 1024 x 1024 in size. Besides the large amount of memory such an image would consume, you may run into problems when using the image as a texture in OpenGL ES or when drawing the image to a view or layer. This size restriction does not apply if you are performing code-based manipulations, such as resizing an image larger than 1024 x 1024 pixels by drawing it to a bitmap-backed graphics context. In fact, you may need to resize an image in this manner (or break it into several smaller images) in order to draw it to one of your views."

Interesting that you see this as a bug, probably you're not alone. Maybe I should use an activity indicator to make it clear that the preview image is temporary.

**Comment by ssfking** [comment]
I see, this makes sense. Thanks a lot for making this awesome library!

**Comment by heitorfr** [comment]
You're welcome. Thanks for the feedback.
